#
# Example .travis.yml file.
#
# Copy to your project and rename to .travis.yml.
# Customize per the instructions below.
#
language: php

php:
  - 7.1

mysql:
  database: wordpress
  username: root
  encoding: utf8

env:
  global:
    # Your Pantheon site's idenfying name (i.e. as shown on the dashboard)
    - TERMINUS_SITE='civictechto'

    # The Pantheon environment to push to after tests succeed.
    # DANGER: This environment will be switched from 'sftp' mode to 'git' mode
    # on every commit to github.  This will ERASE any uncommitted change made in
    # 'sftp' mode.  It is therefore advisable to avoid using 'sftp' mode on
    # the environment you select here. Create a multidev branch specifically for
    # use by Travis.
    - TERMINUS_ENV='dev'

    # SECRET/PRIVATE VARIABLES
    #
    # These are created by using the travis command locally to encrypt some values.
    #
    # See: http://docs.travis-ci.com/user/build-configuration/#Secure-environment-variables
    #
    # PANTHEON_PASS environment variable: represents the Pantheon account password for
    # the above encrypted e-mail address. Run:
    #
    # travis encrypt TERMINUS_TOKEN='my_machine_token'
    #
    - secure: "ZgkOFbIMQfew3mBPeycU1Jr9NyIR7jLbL/Mq/901YoNt8eAvYHskDp+F0CZze39KV7soD/m4Hxspp9NR6GcEp2+1tTCRHrqQ9cLNfPMD3R0ETormZawgrdcjDIIrAHmhok/RkPUMwo1kKsOh2MPfeeL7OeezgCiBs1mC8cYRuZXdyn995m0vJxa0WIXnOAkLYbPeeH/OV8QMy6XNi8wf80dXlQFPZSUNWmG+oqTwqgegV27K9Ll7+Qo9SKQmosn8xeSxJH4+Bbi7HSN8OGpPyjbjpWDexi2rRDZ2KQgphpWa+sB0442Bi33YUYbW0GBQd03kJmnO1ZlcYqydlTNPA+D7zlxiZS4LLcXq9O2Aw8YYBCV0tuMjmI4ggxz3jI9cSA68a/gb28JOH+xwdQm69EpYAIswjRPvL6ffc/cmCidLrc9Kmp26fWgXZsrAD1uhVnxertXIPiHtfwGsCiMvRVxClXsI5s8vrPbUUnw9MjBGIIuRXQllm8K4sL7k6h8pF+1DNvUMZHKGCalm3QfCamRefVjoLgTSqnLfk4Vumguho5VcTneHPBqj25Y1gA1NgqmdbQ6NRGOOWuxrvBI2PBBxpF1x6nu+RT+DayMG5dCG0q7fvKhJrLinjyWw8U+/Esbiogn8YE8q0Ju0nL89y/+oB6WKBzDzwqczj0PXw+U="

before_install:
  # Make sure composer is up-to-date
  - composer self-update
  # Get netstat
  - sudo apt-get update -qq
  - sudo apt-get install net-tools


install:
  # Dummy install script
  - true

script:
  # Dummy script for no tests
  - true

after_success:
  # Place a passphrase-free ssh key so that you can clone and push to your
  # Pantheon git repository.
  #
  # Use the travis encrypt-file command to generate your own.
  #
  # See: http://docs.travis-ci.com/user/encrypting-files/
  #
  - web/private/scripts/set-up-globals.sh
  - web/private/scripts/deploy-to-pantheon.sh

after_failure:
  - if [ -f $HOME/server.log ] ; then echo "Server log:" && cat $HOME/server.log ; fi

after_script:
  - bin/stop-webserver
  - rm $HOME/server.log

notifications:
  email: false
